# Generated by Django 5.2.5 on 2025-08-30 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_tag_post_category_post_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_post', '创建文章'), ('update_post', '更新文章'), ('delete_post', '删除文章'), ('create_user', '用户注册')], max_length=20, verbose_name='操作类型')),
                ('description', models.CharField(max_length=200, verbose_name='操作描述')),
                ('target_title', models.CharField(blank=True, max_length=200, verbose_name='目标对象标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '活动日志',
                'verbose_name_plural': '活动日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
